title: Linguagem C
description: Estudos 
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
